### PR TITLE
remove container dependency & implement usemaxfontsize

### PR DESCRIPTION
**Pull request by nischi**
instead of container use direct parent element that we can use this
directive in variable template combination

Add possibility to set maxfontsize from the element. if set to true the maxfontsize automaticaly set to the original font size of the element

### CODE REVIEW

**Comment by nischi** [comment]
Would be nice if you can compile a new version for npm :)

**Comment by thisloke** [comment]
Thanks for your time and for your improvements!

I'm adding some fixes and also the possibility to use container or not, because there are many cases that need to specify a container.

In few minutes i'll publish a new version.

**Comment by nischi** [comment]
awesome!

**Comment by thisloke** [comment]
Version 1.0.18!  🥇

**Pull request merged**
